//The try statement allows you to define a block of code to be tested for errors while it is being executed.
//The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.

console.log("hello");
console.log("hello1");
// let a = 4;
try {
    console.log(a);
}catch {
    console.log("caught an error .... a is not defined");
    console.log(err);
}
console.log("hello2");
console.log("hello3");
console.log("hello4");